### ISSUE TITLE
ISO8601 DateTime to Timestamp fails when milliseconds not specified

### ISSUE THREAD

**Issue by ciozi137** [LabVIEW-Open-Source/Epoch-Time#14]
Conversion fails when milliseconds are not specified in the ISO8601 DateTime String:

OK:
<img width="628" alt="Screenshot 2024-10-19 at 1 21 39 PM" src="https://github.com/user-attachments/assets/70e340bf-b222-4868-a94b-1861fab4de2d">

Not OK:
<img width="610" alt="Screenshot 2024-10-19 at 1 21 52 PM" src="https://github.com/user-attachments/assets/43785961-dd9d-4779-85fc-2b668f9a8947">

_Originally posted by @ciozi137 in https://github.com/LabVIEW-Open-Source/Epoch-Time/issues/11#issuecomment-2424099145_

**Comment by ciozi137** [comment]
@francois-normandin unfortunately is not working for strict and not strict ISO 8601. And only for 3 (or more?) millisecond digits:
<img width="819" alt="image" src="https://github.com/user-attachments/assets/aad006d9-79ff-43b8-8028-c5c2716c7adf">

**Comment by ciozi137** [comment]
regex:
 ^([0-9]{4})-?(1[0-2]|0[1-9])-?(3[01]|0[1-9]|[12][0-9])([T])([0-9]{2}):([0-9]{2}):([0-9]{2})**\.([0-9]{3})**(.*)

change to:
^([0-9]{4})-?(1[0-2]|0[1-9])-?(3[01]|0[1-9]|[12][0-9])([T])([0-9]{2}):([0-9]{2}):([0-9]{2})**(?:\.([0-9]+))?**(.*)

captures the millisecond field (or not):
<img width="819" alt="Screenshot 2024-10-20 at 9 58 05 AM" src="https://github.com/user-attachments/assets/0fe885f7-6b13-4f20-9b2d-8354f70c1c81">
<img width="811" alt="Screenshot 2024-10-20 at 9 58 26 AM" src="https://github.com/user-attachments/assets/380a0f8c-77d5-48f8-8af0-3b570f6729eb">


But then the logical OR will be False here:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/688c8b9e-1e20-4343-abe1-58ecdf7ebf93">

so still needs a little tweaking

**Comment by ciozi137** [comment]
One more thing I noticed: there is no case for time only, which should also be allowed

**Comment by francois-normandin** [comment]
There is a fix for this in the iso8601_test branch

**Comment by francois-normandin** [comment]
After splitting the conversion into separate Date & Time conversions, the logic has been adjusted to require only hours to be filled before moving to next stage of the conversion.
This allows handling of milliseconds when not defined, but also to support 12,6 or 12:12,6 for instance.

![image](https://github.com/user-attachments/assets/5417298d-b5ca-4d40-8df8-323fe8af5845)

**Comment by francois-normandin** [comment]
Unit tests to track the fix.
![image](https://github.com/user-attachments/assets/fc692df5-ca33-4735-a215-11f1a4d006b4)

**Comment by francois-normandin** [comment]
merged to master branch
